
# API Version
#
# Core Kubernetes resources ke liye v1 API use hoti hai.
apiVersion: v1


# Resource Type
#
# Secret sensitive information store karne ke liye use hota hai.
#
# Examples:
# - Passwords
# - API Keys
# - Tokens
# - Database Credentials
# - JWT Secrets
#
# ConfigMap ke comparison me sensitive data ke liye better option hai.
kind: Secret


metadata:

  # Secret ka naam
  #
  # Deployment is secret ko reference karega.
  name: easyshop-secrets

  # Namespace jahan secret create hoga.
  namespace: easyshop


# Secret Type
#
# Opaque = Generic Secret
#
# Kubernetes ka default secret type.
type: Opaque


# ==================================================
# Secret Values
# ==================================================

# stringData use karne se plain text likh sakte ho.
#
# Kubernetes automatically ise base64 me convert karke
# etcd me store kar deta hai.

stringData:

  # JWT Token Sign Karne Ke Liye Secret Key
  #
  # Login ke baad jo JWT token generate hota hai
  # usse sign aur verify karne ke liye use hota hai.
  #
  # Agar ye leak ho jaye:
  # Attacker fake JWT tokens generate kar sakta hai.
  JWT_SECRET: "change-this-in-production"


  # NextAuth Secret
  #
  # NextAuth sessions aur authentication encryption
  # ke liye use karta hai.
  #
  # Production me strong random value honi chahiye.
  NEXTAUTH_SECRET: "change-this-in-production"

